# Лучшие параметры по результатам экспериментов
# Run: model_XGBoost
# ROC-AUC: 0.9249
# URL: http://158.160.2.37:5000/#/experiments/20/runs/6bb725f6e1bc4a0b965d8e0daa2619c0

process_data:
  features:
    - age
    - workclass
    - education
    - marital.status
    - occupation
    - relationship
    - race
    - sex
    - capital.gain
    - capital.loss
    - hours.per.week
    - native.country
  train_size: 10000

train:
  model_type: XGBoost
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1

evaluate:
  metrics:
    - accuracy
    - f1
    - roc_auc
    - precision
    - recall
